CREATE TABLE [dbo].[CPU]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UsersID] INT NOT NULL, 
    [TotalClock] FLOAT NULL, 
    CONSTRAINT [FK_CPU_ToUsers] FOREIGN KEY (UsersID) REFERENCES Users(UsersID)
)
