CREATE TABLE [dbo].[GPU]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UsersID] INT NOT NULL, 
    [TotalLoad] FLOAT NULL, 
    CONSTRAINT [FK_GPU_ToUsers] FOREIGN KEY (UsersID) REFERENCES Users(UsersID)
)
