CREATE TABLE [dbo].[RAM]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UsersID] INT NOT NULL, 
    [InUse] NCHAR(10) NULL, 
    CONSTRAINT [FK_RAM_ToUsers] FOREIGN KEY (UsersID) REFERENCES Users(UsersID)
)
